spring:
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 注意数据库本地是spring_db
    url: jdbc:mysql://localhost:3306/spring_db?serverTimezone=UTC

server:
  port: 8080

# mybatis的日志信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
